"""Seed data Rapat Harmonisasi Jan-Apr 2026. Total ~50 record."""

from app import create_app
from models import db, RapatHarmonisasi
from datetime import date

DATA = [
    # ===== JANUARI (7) =====
    (
        date(2026, 1, 6),
        "Kabupaten Garut",
        "Raperda (DPRD)",
        "Propemperda",
        "Kesehatan",
        "Penyelenggaraan Kesehatan Masyarakat",
        "Tim Kerja 4",
        "Selesai",
        "Normal",
    ),
    (
        date(2026, 1, 6),
        "Kabupaten Garut",
        "Raperda (DPRD)",
        "Propemperda",
        "Pendidikan",
        "Wajib Belajar Pendidikan Dasar",
        "Tim Kerja 4",
        "Selesai",
        "Normal",
    ),
    (
        date(2026, 1, 13),
        "Kota Tasikmalaya",
        "Raperkada",
        "Propemperkada",
        "Urusan Unsur Penunjang (perencanaan, pengawasan, kepegawaian, keuangan, pendidikan dan latihan, penelitian dan pengembangan)",
        "Pedoman Penyusunan Anggaran Pendapatan dan Belanja Daerah Tahun 2026",
        "Tim Kerja 1",
        "Selesai",
        "One Day Service",
    ),
    (
        date(2026, 1, 13),
        "Kota Tasikmalaya",
        "Raperkada",
        "Propemperkada",
        "Perhubungan",
        "Penyelenggaraan Lalu Lintas dan Angkutan Jalan",
        "Tim Kerja 1",
        "Dikembalikan",
        "One Day Service",
    ),
    (
        date(2026, 1, 20),
        "Kabupaten Sumedang",
        "Raperda (Pemda)",
        "Propemperda",
        "Perumahan Rakyat dan Kawasan Permukiman",
        "Penyelenggaraan Perumahan dan Kawasan Permukiman",
        "Tim Kerja 3",
        "Selesai",
        "Normal",
    ),
    (
        date(2026, 1, 29),
        "Kabupaten Indramayu",
        "Raperkada",
        "Propemperkada",
        "Urusan Unsur Penunjang (perencanaan, pengawasan, kepegawaian, keuangan, pendidikan dan latihan, penelitian dan pengembangan)",
        "Pedoman Pemberian Tambahan Penghasilan Pegawai Aparatur Sipil Negara",
        "Tim Kerja 2",
        "Selesai",
        "One Day Service",
    ),
    (
        date(2026, 1, 29),
        "Kabupaten Indramayu",
        "Raperkada",
        "Propemperkada",
        "Urusan Unsur Pendukung (Sekretariat Daerah)",
        "Perhitungan dan Penetapan Tarif Pemakaian Air Minum Perusahaan Umum Daerah Air Minum Tirta Darma Ayu Kabupaten Indramayu",
        "Tim Kerja 2",
        "Selesai",
        "Normal",
    ),
    # ===== FEBRUARI (8) =====
    (
        date(2026, 2, 3),
        "Kabupaten Subang",
        "Raperkada",
        "Propemperkada",
        "Komunikasi dan Informatika",
        "Pedoman Penyelenggaraan Komunikasi Publik",
        "Tim Kerja 1",
        "Dikembalikan",
        "One Day Service",
    ),
    (
        date(2026, 2, 3),
        "Kabupaten Subang",
        "Raperkada",
        "Propemperkada",
        "Urusan Unsur Penunjang (perencanaan, pengawasan, kepegawaian, keuangan, pendidikan dan latihan, penelitian dan pengembangan)",
        "Perubahan Anggaran Pendapatan dan Belanja Daerah Tahun Anggaran 2026",
        "Tim Kerja 1",
        "Selesai",
        "One Day Service",
    ),
    (
        date(2026, 2, 10),
        "Kabupaten Kuningan",
        "Raperda (Pemda)",
        "Propemperda",
        "Pekerjaan Umum dan Penataan Ruang",
        "Penyelenggaraan Jalan dan Jembatan",
        "Tim Kerja 2",
        "Selesai",
        "Normal",
    ),
    (
        date(2026, 2, 10),
        "Kabupaten Kuningan",
        "Raperkada",
        "Propemperkada",
        "Kesehatan",
        "Penyelenggaraan Pelayanan Kesehatan",
        "Tim Kerja 2",
        "Selesai",
        "One Day Service",
    ),
    (
        date(2026, 2, 17),
        "Kota Banjar",
        "Raperda (DPRD)",
        "Propemperda",
        "Pemberdayaan Perempuan dan Pelindungan Anak",
        "Perlindungan Perempuan dan Anak",
        "Tim Kerja 4",
        "Selesai",
        "Normal",
    ),
    (
        date(2026, 2, 17),
        "Kota Cirebon",
        "Raperkada",
        "Di luar Propemperkada",
        "Perhubungan",
        "Rasionalisasi Trayek Angkutan Kota",
        "Tim Kerja 3",
        "Selesai",
        "Normal",
    ),
    (
        date(2026, 2, 24),
        "Kabupaten Pangandaran",
        "Raperkada",
        "Di luar Propemperkada",
        "Pekerjaan Umum dan Penataan Ruang",
        "Rencana Detail Tata Ruang Kabupaten Pangandaran",
        "Tim Kerja 2",
        "Selesai",
        "Normal",
    ),
    (
        date(2026, 2, 24),
        "Kabupaten Pangandaran",
        "Raperda (Pemda)",
        "Propemperda",
        "Kepemudaan dan Olah Raga",
        "Pembinaan dan Pengembangan Kepemudaan",
        "Tim Kerja 2",
        "Selesai",
        "One Day Service",
    ),
    # ===== MARET (8) =====
    (
        date(2026, 3, 3),
        "Kabupaten Bogor",
        "Raperkada",
        "Propemperkada",
        "Urusan Unsur Penunjang (perencanaan, pengawasan, kepegawaian, keuangan, pendidikan dan latihan, penelitian dan pengembangan)",
        "Pedoman Pengelolaan Keuangan Daerah",
        "Tim Kerja 1",
        "Selesai",
        "One Day Service",
    ),
    (
        date(2026, 3, 3),
        "Kabupaten Bogor",
        "Raperda (DPRD)",
        "Propemperda",
        "Perindustrian",
        "Rencana Pembangunan Industri Kabupaten Bogor",
        "Tim Kerja 1",
        "Selesai",
        "Normal",
    ),
    (
        date(2026, 3, 10),
        "Kabupaten Majalengka",
        "Raperkada",
        "Propemperkada",
        "Urusan Unsur Pendukung (Sekretariat Daerah)",
        "Tunjangan Hari Raya bagi Pegawai Negeri Sipil",
        "Tim Kerja 4",
        "Selesai",
        "One Day Service",
    ),
    (
        date(2026, 3, 10),
        "Kabupaten Purwakarta",
        "Raperda (DPRD)",
        "Propemperda",
        "Pendidikan",
        "Penyelenggaraan Pendidikan",
        "Tim Kerja 3",
        "Dikembalikan",
        "Normal",
    ),
    (
        date(2026, 3, 17),
        "Kabupaten Cirebon",
        "Raperkada",
        "Propemperkada",
        "Pemberdayaan Masyarakat dan Desa",
        "Pemberdayaan Masyarakat di Bidang Kesehatan",
        "Tim Kerja 3",
        "Selesai",
        "One Day Service",
    ),
    (
        date(2026, 3, 17),
        "Kota Sukabumi",
        "Raperda (Pemda)",
        "Propemperda",
        "Perindustrian",
        "Rencana Induk Perindustrian Kota Sukabumi",
        "Tim Kerja 4",
        "Selesai",
        "Normal",
    ),
    (
        date(2026, 3, 24),
        "Kota Banjar",
        "Raperkada",
        "Propemperkada",
        "Komunikasi dan Informatika",
        "Pedoman Pengelolaan Media Sosial Pemerintah Daerah",
        "Tim Kerja 4",
        "Selesai",
        "One Day Service",
    ),
    (
        date(2026, 3, 31),
        "Kabupaten Sumedang",
        "Raperkada",
        "Propemperkada",
        "Urusan Unsur Pendukung (Sekretariat Daerah)",
        "Pembayaran Tunjangan Kinerja Daerah",
        "Tim Kerja 3",
        "Selesai",
        "One Day Service",
    ),
    # ===== APRIL (27) =====
    (
        date(2026, 4, 1),
        "Kota Bekasi",
        "Raperkada",
        "Propemperkada",
        "Komunikasi dan Informatika",
        "Penyelenggaraan Infrastruktur Pasif Telekomunikasi",
        "Tim Kerja 3",
        "Selesai",
        "One Day Service",
    ),
    (
        date(2026, 4, 1),
        "Kota Bandung",
        "Raperkada",
        "Propemperkada",
        "Pendidikan",
        "Raperwal Kota Bandung tentang Bantuan Operasional Sekolah Daerah",
        "Tim Kerja 2",
        "Selesai",
        "Normal",
    ),
    (
        date(2026, 4, 2),
        "Kabupaten Bekasi",
        "Raperkada",
        "Propemperkada",
        "Urusan Unsur Penunjang (perencanaan, pengawasan, kepegawaian, keuangan, pendidikan dan latihan, penelitian dan pengembangan)",
        "Tata Cara Pemberian Dan Pemanfaatan Insentif Pemungutan Pajak Daerah Dan Retribusi Daerah Tahun 2026",
        "Tim Kerja 2",
        "Selesai",
        "One Day Service",
    ),
    (
        date(2026, 4, 2),
        "Kota Sukabumi",
        "Raperkada",
        "Propemperkada",
        "Urusan Unsur Pendukung (Sekretariat Daerah)",
        "Tunjangan Komunikasi Intensif, Tunjangan Reses Pimpinan dan Anggota DPRD serta Dana Operasional Pimpinan DPRD",
        "Tim Kerja 4",
        "Selesai",
        "One Day Service",
    ),
    (
        date(2026, 4, 2),
        "Kota Sukabumi",
        "Raperkada",
        "Propemperkada",
        "Urusan Unsur Pendukung (Sekretariat Daerah)",
        "Kemampuan Keuangan Daerah",
        "Tim Kerja 4",
        "Selesai",
        "One Day Service",
    ),
    (
        date(2026, 4, 7),
        "Kabupaten Karawang",
        "Raperda (DPRD)",
        "Propemperda",
        "Perpustakaan",
        "Penyelenggaraan Perpustakaan",
        "Tim Kerja 1",
        "Selesai",
        "One Day Service",
    ),
    (
        date(2026, 4, 7),
        "Kota Depok",
        "Raperda (Pemda)",
        "Propemperda",
        "Perindustrian",
        "Rencana Pembangunan Industri Kota Depok Tahun 2026-2046",
        "Tim Kerja 2",
        "Selesai",
        "One Day Service",
    ),
    (
        date(2026, 4, 7),
        "Kota Depok",
        "Raperda (Pemda)",
        "Propemperda",
        "Urusan Unsur Penunjang (perencanaan, pengawasan, kepegawaian, keuangan, pendidikan dan latihan, penelitian dan pengembangan)",
        "Perubahan Ketiga Atas Peraturan Daerah Nomor 10 Tahun 2016 tentang Pembentukan dan Susunan Perangkat Daerah Kota Depok",
        "Tim Kerja 2",
        "Selesai",
        "One Day Service",
    ),
    (
        date(2026, 4, 7),
        "Kota Depok",
        "Raperda (Pemda)",
        "Propemperda",
        "Perhubungan",
        "Penyelenggaraan Perhubungan",
        "Tim Kerja 2",
        "Selesai",
        "One Day Service",
    ),
    (
        date(2026, 4, 7),
        "Kota Bogor",
        "Raperda (DPRD)",
        "Propemperda",
        "Perumahan Rakyat dan Kawasan Permukiman",
        "Penyelenggaraan Rumah Susun",
        "Tim Kerja 3",
        "Selesai",
        "Normal",
    ),
    (
        date(2026, 4, 8),
        "Kota Cimahi",
        "Raperkada",
        "Propemperkada",
        "Urusan Unsur Penunjang (perencanaan, pengawasan, kepegawaian, keuangan, pendidikan dan latihan, penelitian dan pengembangan)",
        "Target Penerimaan Pajak Daerah dan Retribusi Daerah Tahun 2026",
        "Tim Kerja 4",
        "Selesai",
        "One Day Service",
    ),
    (
        date(2026, 4, 8),
        "Kabupaten Ciamis",
        "Raperkada",
        "Propemperkada",
        "Urusan Unsur Penunjang (perencanaan, pengawasan, kepegawaian, keuangan, pendidikan dan latihan, penelitian dan pengembangan)",
        "Perubahan Atas Peraturan Bupati Ciamis Nomor 42 Tahun 2025 tentang Analisis Standar Belanja",
        "Tim Kerja 1",
        "Selesai",
        "One Day Service",
    ),
    (
        date(2026, 4, 8),
        "Kabupaten Ciamis",
        "Raperkada",
        "Propemperkada",
        "Komunikasi dan Informatika",
        "Pedoman Pengelolaan Layanan Informasi dan Dokumentasi di Lingkungan Pemerintah Kabupaten Ciamis",
        "Tim Kerja 1",
        "Dikembalikan",
        "One Day Service",
    ),
    (
        date(2026, 4, 9),
        "Kota Bogor",
        "Raperda (Pemda)",
        "Propemperda",
        "Kesehatan",
        "Penyelenggaraan Kesehatan",
        "Tim Kerja 3",
        "Selesai",
        "Normal",
    ),
    (
        date(2026, 4, 9),
        "Kota Bogor",
        "Raperkada",
        "Di luar Propemperkada",
        "Pemberdayaan Masyarakat dan Desa",
        "Perubahan Perwal Nomor 28 Tahun 2025 tentang Lembaga Kemasyarakatan Kelurahan",
        "Tim Kerja 3",
        "Selesai",
        "Normal",
    ),
    (
        date(2026, 4, 9),
        "Kota Bogor",
        "Raperkada",
        "Di luar Propemperkada",
        "Perhubungan",
        "Rasionalisasi, Peremajaan, dan Penghapusan Kendaraan Bermotor Umum dalam Trayek",
        "Tim Kerja 3",
        "Selesai",
        "Normal",
    ),
    (
        date(2026, 4, 10),
        "Kabupaten Bandung Barat",
        "Raperkada",
        "Propemperda",
        "Pekerjaan Umum dan Penataan Ruang",
        "Strategi Sanitasi Kabupaten Bandung Barat Tahun 2025-2029",
        "Tim Kerja 2",
        "Selesai",
        "One Day Service",
    ),
    (
        date(2026, 4, 10),
        "Kabupaten Bandung Barat",
        "Raperkada",
        "Propemperda",
        "Pekerjaan Umum dan Penataan Ruang",
        "Kebijakan dan Strategi Daerah Penyelenggaraan Sistem Penyediaan Air Minum Tahun 2025-2029",
        "Tim Kerja 2",
        "Selesai",
        "One Day Service",
    ),
    (
        date(2026, 4, 13),
        "Kota Bandung",
        "Raperkada",
        "Propemperkada",
        "Pendidikan",
        "Perubahan Peraturan Wali Kota Nomor 24 Tahun 2025 tentang Sistem Penerimaan Murid Baru pada TK, SD, dan SMP",
        "Tim Kerja 3",
        "Selesai",
        "One Day Service",
    ),
    (
        date(2026, 4, 13),
        "Kota Bandung",
        "Raperkada",
        "Propemperkada",
        "Pendidikan",
        "Bantuan Pendidikan bagi Peserta Didik Rawan Melanjutkan Pendidikan pada Jenjang Pendidikan Dasar dan Perguruan Tinggi",
        "Tim Kerja 3",
        "Selesai",
        "Normal",
    ),
    (
        date(2026, 4, 14),
        "Kabupaten Cianjur",
        "Raperda (DPRD)",
        "Propemperda",
        "Kesehatan",
        "Kesehatan",
        "Tim Kerja 4",
        "Selesai",
        "Normal",
    ),
    (
        date(2026, 4, 14),
        "Kabupaten Cianjur",
        "Raperda (DPRD)",
        "Propemperda",
        "Kepemudaan dan Olah Raga",
        "Keolahragaan",
        "Tim Kerja 4",
        "Selesai",
        "Normal",
    ),
    (
        date(2026, 4, 14),
        "Kabupaten Cianjur",
        "Raperda (DPRD)",
        "Propemperda",
        "Pemberdayaan Perempuan dan Pelindungan Anak",
        "Pemberdayaan dan Perlindungan Perempuan",
        "Tim Kerja 4",
        "Selesai",
        "Normal",
    ),
    (
        date(2026, 4, 21),
        "Kota Depok",
        "Raperkada",
        "Propemperkada",
        "Perpustakaan",
        "Penyelenggaraan Perpustakaan Kota Depok",
        "Tim Kerja 2",
        "Selesai",
        "One Day Service",
    ),
    (
        date(2026, 4, 28),
        "Kabupaten Karawang",
        "Raperkada",
        "Propemperkada",
        "Kesehatan",
        "Rencana Aksi Daerah Pencegahan Stunting",
        "Tim Kerja 1",
        "Selesai",
        "One Day Service",
    ),
    (
        date(2026, 4, 28),
        "Kabupaten Bekasi",
        "Raperda (Pemda)",
        "Propemperda",
        "Perumahan Rakyat dan Kawasan Permukiman",
        "Penyediaan Rumah Susun Sederhana Sewa",
        "Tim Kerja 2",
        "Selesai",
        "Normal",
    ),
]

app = create_app()

with app.app_context():
    existing = RapatHarmonisasi.query.count()
    if existing > 0:
        print(
            f"Database sudah berisi {existing} data. Hapus dulu instance/dasborpim.db jika ingin re-seed."
        )
    else:
        for row in DATA:
            r = RapatHarmonisasi(
                tanggal_rapat=row[0],
                daerah=row[1],
                jenis=row[2],
                program_pembentukan=row[3],
                urusan_pemerintahan=row[4],
                nama_raperda=row[5],
                tim_kerja=row[6],
                hasil=row[7],
                metode=row[8],
                created_by=1,
            )
            db.session.add(r)
        db.session.commit()
        total = RapatHarmonisasi.query.count()
        print(f"Berhasil memasukkan {total} data rapat harmonisasi (Jan-Apr 2026).")
